CREATE TABLE IF NOT EXISTS COMMITS
(
    BUCKET_ID varchar(64) charset utf8 NOT NULL,
    STREAM_ID varchar(64) charset utf8 NOT NULL,
    STREAM_ID_ORIGINAL varchar(1000) charset utf8 NOT NULL,
    STREAM_REVISION int NOT NULL CHECK (COMMITS.STREAM_REVISION > 0),
    ITEMS tinyint NOT NULL CHECK (ITEMS > 0),
    COMMIT_ID VARCHAR(64) NOT NULL CHECK (COMMIT_ID != 0),
    COMMIT_SEQUENCE int NOT NULL CHECK (COMMITS.COMMIT_SEQUENCE > 0),
    COMMIT_STAMP bigint NOT NULL,
    CHECKPOINT_NUMBER bigint AUTO_INCREMENT,
    DISPATCHED bit NOT NULL DEFAULT 0,
    HEADERS blob NULL,
    PAYLOAD mediumblob NOT NULL,
    PRIMARY KEY (CHECKPOINT_NUMBER)

);

# ALTER TABLE COMMITS ADD INDEX (BUCKET_ID, STREAM_ID, COMMIT_SEQUENCE);
# ALTER TABLE COMMITS ADD INDEX (BUCKET_ID, STREAM_ID, COMMIT_ID);
# ALTER TABLE COMMITS ADD INDEX (BUCKET_ID, STREAM_ID, STREAM_REVISION, ITEMS);
# ALTER TABLE COMMITS ADD INDEX (DISPATCHED);
# ALTER TABLE COMMITS ADD INDEX (COMMIT_STAMP);

CREATE TABLE IF NOT EXISTS SNAPSHOTS
(
    BUCKET_ID varchar(40) charset utf8 NOT NULL,
    STREAM_ID varchar(40) charset utf8 NOT NULL,
    STREAM_REVISION int NOT NULL CHECK (SNAPSHOTS.STREAM_REVISION > 0),
    PAYLOAD blob NOT NULL,
    CONSTRAINT PK_Snapshots PRIMARY KEY (BUCKET_ID, STREAM_ID, STREAM_REVISION)
);